# Generated by Django 5.0.4 on 2026-03-19 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positive = stock in, negative = stock out')),
                ('reason', models.CharField(choices=[('manual', 'Manual Adjustment'), ('sale', 'Sale'), ('purchase', 'Purchase / Restock'), ('return', 'Customer Return'), ('damage', 'Damage / Write-off'), ('correction', 'Stock Correction')], default='manual', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='products.product')),
            ],
            options={
                'db_table': 'inventory_stockadjustment',
                'ordering': ['-created_at'],
            },
        ),
    ]
