# Generated by Django 5.0.4 on 2026-03-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Store', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, verbose_name='PAN Number')),
                ('vat_no', models.CharField(blank=True, max_length=20, verbose_name='VAT Number')),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
                'db_table': 'settings_companyprofile',
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_alert', models.BooleanField(default=True)),
                ('low_stock_email', models.EmailField(blank=True, max_length=254)),
                ('daily_report', models.BooleanField(default=False)),
                ('daily_report_email', models.EmailField(blank=True, max_length=254)),
                ('order_confirm', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Config',
                'verbose_name_plural': 'Notification Config',
                'db_table': 'settings_notificationconfig',
            },
        ),
        migrations.CreateModel(
            name='TaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=13.0, max_digits=5)),
                ('vat_enabled', models.BooleanField(default=True)),
                ('pan_on_receipt', models.BooleanField(default=True)),
                ('vat_on_receipt', models.BooleanField(default=True)),
                ('tax_inclusive', models.BooleanField(default=False, help_text='If True, prices include tax; otherwise tax is added on top.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configuration',
                'db_table': 'settings_taxconfig',
            },
        ),
    ]
